### ISSUE TITLE
Templating init failed Datasource named Holocron was not found

### ISSUE THREAD

**Issue by cm2339** [kernelkaribou/synology-monitoring#2]
After importing the json file, i get the error `Templating init failed
Datasource named Holocron was not found` and there's no data. I tried creating a dashboard from scratch and was able to pull data from influxdb so i'm guessing there's something my Grafana doesn't like from your template. Any ideas on how to fix are appreciated!

**Comment by MTrab** [comment]
Same issue noted here.

**Comment by kernelkaribou** [comment]
Sorry, just saw this.  This was due to the variables having a defined data source. I updated the JSON template to use your default grafana datasource.  You can edit the data source in the Variables of the dashboard if needed (as well as Visualizations themselves)

Marking as closed as this should be fixed.

**Comment by MTrab** [comment]
Still seeing the same error with the new JSON - issue not fixed.

**Comment by MTrab** [comment]
And I don't see any variable to set the datasource

![image](https://user-images.githubusercontent.com/14296463/57982379-0f53e800-7a45-11e9-8bfc-bf80e7ba56b8.png)

**Comment by kernelkaribou** [comment]
If you click on the variables themselves, you will see a data source. So for instance click on $nas_host

![image](https://user-images.githubusercontent.com/25406580/57983368-9fc70400-7a16-11e9-9b56-24c140e92a6c.png)

I just reviewed the JSON template and I believe that when I uploaded the new one it didnt overwrite or I  made a mistake on the commit.  Confirmed that the Synology_dashboard.json has no references to Holocron at this point.

**Comment by Buster1959** [comment]
Got this working fine, thank you for your work put in. Could I suggest that you put "change_me" or something similar in the json for people to search and replace, with their datasource.
Then they can put the Dashboard in edit mode and check each panel Query to make sure it is correct. 
Thanks again, Brent

**Comment by kernelkaribou** [comment]
Should be addressed in latest template update.
